export const sapProjects = [
  {
    id: "petro-cloud",
    industry: "Integrated Petrochemicals & Refining",
    project: "SAP S/4HANA Private Cloud Implementation",
    position: "Technical ABAP Consultant",
    period: "Key Enterprise Program",
    badge: "Clean-Core Architecture",
    tags: ["S/4HANA Private Cloud", "Clean-Core", "ABAP Cloud", "BTP", "RAP", "Fiori / UI5", "CDS / AMDP", "ATC"],
    summary: "Architected Clean-Core extensions and modern ABAP Cloud solutions on SAP S/4HANA Private Cloud.",
    responsibilities: [
      "Designed Clean-Core extension architecture (in-app, ABAP Cloud, and BTP side-by-side).",
      "Built modern ABAP for HANA solutions using CDS Views, AMDP, RAP (RESTful Application Programming Model), and OData.",
      "Developed SAP Fiori Elements and custom SAPUI5 user applications.",
      "Ensured code excellence via ATC (ABAP Test Cockpit), ABAP Unit tests, performance tuning, and security authorizations.",
      "Led Unit Testing, System Integration Testing (SIT), and User Acceptance Testing (UAT) issue fixes.",
    ],
  },
  {
    id: "agro-uk",
    industry: "Agro & Food Industry",
    project: "SAP S/4HANA Implementation (UK)",
    position: "Technical ABAP Consultant",
    period: "Enterprise Rollout",
    badge: "UK S/4HANA Rollout",
    tags: ["S/4HANA", "HANA Coding", "Smart Forms", "BDC", "BAPI", "RFC", "ALV Grid"],
    summary: "Delivered core S/4HANA UK implementation across multiple functional modules.",
    responsibilities: [
      "Partnered with Functional Teams across multiple modules to design technical specifications.",
      "Implemented ABAP programming optimized for SAP HANA database execution.",
      "Developed custom Smart Forms and SAPscript documents for supply chain and commercial dispatch.",
      "Engineered Batch Data Command (BDC) interfaces and custom ALV Grid / List analytical reports.",
      "Connected BAPI and RFC communication pipelines with thorough defect resolution.",
    ],
  },
  {
    id: "agri-food",
    industry: "Agriculture & Food Industry",
    project: "SAP S/4HANA Implementation",
    position: "Technical ABAP Consultant",
    period: "Full Lifecycle",
    badge: "Full Lifecycle",
    tags: ["S/4HANA", "Dialog Programming", "BAPI", "RFC", "ALV List", "HANA DB"],
    summary: "Full lifecycle S/4HANA module implementation and custom dialog transaction development.",
    responsibilities: [
      "Collaborated closely with functional leads to translate operational business requirements into ABAP logic.",
      "Programmed interactive custom SAP GUI Dialog Screens (screen painter, PBO/PAI module pools).",
      "Created high-volume ALV Grid reporting for inventory and operational tracking.",
      "Constructed transactional BAPI wrappers and RFC endpoints for enterprise workflows.",
    ],
  },
  {
    id: "energy-util-s4",
    industry: "Energy & Utilities Industry",
    project: "SAP S/4HANA Implementation",
    position: "Technical ABAP Consultant",
    period: "Enterprise Implementation",
    badge: "Core Utilities",
    tags: ["S/4HANA", "User Exits", "BAdIs", "Smart Forms", "BDC", "BAPI"],
    summary: "Custom S/4HANA enhancements, BAdIs, and core utility billing/distribution reporting.",
    responsibilities: [
      "Designed and implemented complex SAP Enhancements: User Exits, BAdIs, and custom enhancement routines.",
      "Crafted automated Batch Data Command (BDC) migration scripts for mass data loading.",
      "Engineered Smart Forms documentation for utility operational records.",
      "Executed testing, performance optimization, and bug fixing throughout SIT/UAT.",
    ],
  },
  {
    id: "energy-bank",
    industry: "Energy & Utilities Industry",
    project: "Enterprise Bank Interface",
    position: "Technical ABAP Consultant",
    period: "Finance Interface",
    badge: "FI Banking Interface",
    tags: ["FI Module", "Banking Interface", "BDC", "BAPI", "RFC", "ALV"],
    summary: "Secure banking payment interface and financial accounting integration.",
    responsibilities: [
      "Developed robust technical interface solutions specifically for the SAP Financial Accounting (FI) module.",
      "Automated bank data processing and transaction reconciliation via BDC & BAPI.",
      "Created transactional audit ALV reports ensuring compliance with enterprise financial controls.",
      "Supported bank integration testing and production cutover.",
    ],
  },
  {
    id: "petro-logistics",
    industry: "Petrochemicals & Chemicals",
    project: "SAP Integration for Logistics System",
    position: "Technical ABAP Consultant",
    period: "Logistics Integration",
    badge: "MM Logistics",
    tags: ["MM Module", "Logistics", "BAPI", "RFC", "BDC", "ALV Reporting"],
    summary: "Material Management (MM) integration for plant logistics and transport tracking.",
    responsibilities: [
      "Specialized in ABAP technical enhancements for the Material Management (MM) module.",
      "Engineered real-time RFC and BAPI interfaces between SAP ERP and third-party logistics systems.",
      "Developed BDC automation for goods movements and inventory movements.",
      "Delivered custom ALV inventory visibility dashboards with dynamic filtering.",
    ],
  },
  {
    id: "transport-ops",
    industry: "Transportation & Logistics",
    project: "Operational Support & Projects",
    position: "SAP ABAP Consultant",
    period: "Operations Support",
    badge: "Continuous Support",
    tags: ["Operations Support", "Smart Forms", "SAPScript", "User Exits", "BAdIs"],
    summary: "Critical enterprise operational support, incident resolution, and document automation.",
    responsibilities: [
      "Provided technical consulting and continuous operational enhancements for business-critical SAP instances.",
      "Maintained and enhanced legacy SAPScript and Smart Forms for transport documents.",
      "Implemented surgical User Exits and BAdIs to enforce custom business validations.",
    ],
  },
  {
    id: "foundations",
    industry: "Engineering Foundation & Bootcamps",
    project: "Professional Bootcamps & Engineering",
    position: "Fellow & Graduate Engineer",
    period: "2021 – 2024",
    badge: "Full-Stack & Cloud",
    tags: ["Generation Thailand (MERN)", "KBTG Kampus (Infra/DevOps)", "SVI Public Co."],
    summary: "Rigorous background in full-stack software development, cloud infrastructure, and program management.",
    responsibilities: [
      "Generation Thailand x GenKX: Junior Software Developer Bootcamp (MERN Stack, SDLC, hands-on agile engineering).",
      "KBTG Kampus: Infrastructure Engineer Bootcamp (DevOps, Cloud Technology, Observability & Tracing).",
      "SVI Public Company Limited: Graduate Engineer – Program Management (SMT-IMT Engineering, cross-functional management).",
    ],
  },
];

export const projectList = [
  {
    id: "Pony Mart",
    name: "Pony Mart E-Commerce",
    category: "Full-Stack Web App",
    tech: "React • Node.js • Express • MongoDB",
    desc: "Comprehensive e-commerce platform built in a collaborative agile environment.",
    liveUrl: "https://jsd-7-cmfm-frontend.vercel.app/",
  },
  {
    id: "CRUD",
    name: "Simple CRUD System",
    category: "Frontend Web Application",
    tech: "JavaScript • HTML5 • CSS3",
    desc: "Interactive records manager demonstrating asynchronous state and DOM manipulation.",
    liveUrl: "https://05-fear-js.vercel.app/",
  },
  {
    id: "Colmar",
    name: "Colmar Academy",
    category: "Responsive Web Portal",
    tech: "HTML5 • Responsive CSS3",
    desc: "Responsive institutional academy landing page focused on mobile-first accessibility.",
    liveUrl: "https://5-fear-colmar.vercel.app/",
  },
];
